# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hnYSJafh6M9q6qr2Y7SxC72pWthMsC7o
"""

import os
import numpy as np
import matplotlib.pyplot as plt

# Sinus funksiyasining grafigini chizish
x = np.linspace(0, 2 * np.pi, 1000)
y = np.sin(x)

plt.figure(figsize=(8, 5))
plt.plot(x, y, label="y = sin(x)", color="blue")
plt.title("Sinus Function")
plt.xlabel("x")
plt.ylabel("sin(x)")
plt.axhline(0, color='black', linewidth=0.5, linestyle='--')
plt.axvline(0, color='black', linewidth=0.5, linestyle='--')
plt.grid(alpha=0.3)
plt.legend()
plt.tight_layout()

# Grafikni saqlash
file_name = "sinus_function_plot.png"
plt.savefig(file_name)
plt.show()

# GitHub uchun faylni yuklash jarayoni
repo_name = "sinus-function-plot"
commit_message = "Add sinus function plot"
github_username = "your_github_username"  # GitHub foydalanuvchi nomingiz
github_token = "your_github_token"       # GitHub tokeningiz (yoki git login orqali foydalaning)

# Git uchun buyruqlar
os.system(f"git init")
os.system(f"git remote add origin https://github.com/{github_username}/{repo_name}.git")
os.system(f"git add {file_name}")
os.system(f"git commit -m \"{commit_message}\"")
os.system(f"git branch -M main")
os.system(f"git push -u origin main")

import os
import numpy as np
import matplotlib.pyplot as plt

# Tasodifiy ma'lumotlarni generatsiya qilish
np.random.seed(42)  # Natijalarni qayta takrorlash uchun
x = np.random.rand(100) * 100  # X koordinatalar (0 dan 100 gacha)
y = np.random.rand(100) * 100  # Y koordinatalar (0 dan 100 gacha)

# Scatter grafikni chizish
plt.figure(figsize=(8, 6))
plt.scatter(x, y, color='blue', alpha=0.7, edgecolor='k')
plt.title("Tasodifiy Scatter Grafiki")
plt.xlabel("X o'qi")
plt.ylabel("Y o'qi")
plt.grid(alpha=0.3)
plt.tight_layout()

# Grafikni saqlash
file_name = "scatter_grafik.png"
plt.savefig(file_name)
plt.show()

# GitHub uchun faylni yuklash jarayoni
repo_name = "scatter-grafik-example"
commit_message = "Add random scatter grafik"
github_username = "your_github_username"  # GitHub foydalanuvchi nomingiz
github_token = "your_github_token"       # GitHub tokeningiz (yoki git login orqali foydalaning)

# Git uchun buyruqlar
os.system(f"git init")
os.system(f"git remote add origin https://github.com/{github_username}/{repo_name}.git")
os.system(f"git add {file_name}")
os.system(f"git commit -m \"{commit_message}\"")
os.system(f"git branch -M main")
os.system(f"git push -u origin main")

import pandas as pd

file_path = '/content/WHO COVID-19 cases (3).csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AF")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases (3).csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AL")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases (3).csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AS")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases (3).csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AD")]
print(filtr)

import pandas as pd

file_path = '/content/WHO COVID-19 cases (3).csv'
df = pd.read_csv(file_path)


sorted_df = df.sort_values(by='Country')

filtr=df[(df['Country_code']=="AO")]
print(filtr)

pip install opencv-python

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("bayroq.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("TATUFF.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google.colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("suniy.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)